services:
  - type: web
    name: poketrade
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn poketrade.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: poketrade.settings
      - key: PYTHON_VERSION
        value: 3.9

