services:
  - type: web
    name: poketradeapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn poketradeapp.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: poketradeapp.settings
      - key: PYTHON_VERSION
        value: 3.9

