# Generated by Django 4.2.20 on 2025-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usercollection_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
