# Generated by Django 4.2.20 on 2025-04-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pokemoncard_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemoncard',
            unique_together={('name', 'hp', 'type')},
        ),
    ]
