# Generated by Django 4.2.20 on 2025-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
