# Generated by Django 4.2.20 on 2025-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='offered_card',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='requested_card',
        ),
        migrations.AddField(
            model_name='traderequest',
            name='offered_cards',
            field=models.ManyToManyField(related_name='offered_in_trades', to='core.pokemoncard'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='requested_cards',
            field=models.ManyToManyField(related_name='requested_in_trades', to='core.pokemoncard'),
        ),
    ]
