# Generated by Django 4.2.20 on 2025-04-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option4',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_property',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('rarity', 'Rarity'), ('element_type', 'Element Type'), ('generation', 'Generation'), ('evolution_stage', 'Evolution Stage'), ('legendary_status', 'Legendary Status'), ('ability', 'Ability'), ('dex_id', 'Dex ID'), ('region', 'Region'), ('base_hp', 'Base HP'), ('type_combination', 'Type Combination')], default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
