name: CI/CD to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push to ACR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/poketradedeploy:latest

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AZURE_AKS_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
