name: Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Authenticate to Azure using your SPN
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2️⃣ Login to your ACR (no username/password needed!)
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: gtpoketradeacr7131.azurecr.io

      # 3️⃣ Build & push your Docker image
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            gtpoketradeacr7131.azurecr.io/poketradeapp:latest

      # 4️⃣ Configure kubectl to talk to your AKS cluster
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: gt-poketrade-rg
          cluster-name: gtpoketrade-aks

      # 5️⃣ Deploy your manifests
      - name: Deploy to AKS
        run: kubectl apply -f k8s/deployment.yaml
